In [1]:
import numpy as np

In [2]:
k = {1: [10, 20, 5], 3:[40, 100, 750], 5:[80, 56, 48]}

In [12]:
max(k, key=k.get)
min(k, key=k.get)

1

In [8]:
max_key = max(k, key=lambda l: k[l])
print(max_key)

5


In [9]:
maxx = max(k.values()) 

In [10]:
keys = [x for x,y in k.items() if y ==maxx]

In [11]:
keys

[5]

In [13]:
max(k, key=lambda x: k[x])

5

In [14]:
max((val, key) for key, val in k.items())[1]

5

In [21]:
y = [2, 3, 1, 0]

In [25]:
s = np.array([
    [44, 58, 79, 80],
    [12, 54, 87, 45],
    [33, 51, 69, 56],
    [92, 23, 64, 78]
])

In [12]:
i = y[:, np.newaxis]
print(i)

[[2]
 [3]
 [1]
 [0]]


In [13]:
print(s[i])

TypeError: only integer scalar arrays can be converted to a scalar index

In [14]:
j = (1, 3)
print(j)

(1, 3)


In [23]:
i = [np.arange(4), y]
print(i)

[array([0, 1, 2, 3]), [2, 3, 1, 0]]


In [26]:
s[np.arange(4), y]

array([79, 45, 51, 92])

In [27]:
s[i]

array([79, 45, 51, 92])